### ISSUE TITLE
Implement deleting a client in Clients table view

### ISSUE THREAD

**Issue by anna-bass** [health-reporter/health-reporter#28]
See the [requirement nr 3 related to clients](https://github.com/BA5S85/health-reporter/wiki/Functional-requirements) and link to the [use case](https://github.com/BA5S85/health-reporter/wiki/_Deleting-clients)

**Comment by BA5S85** [comment]
Link to the corresponding use case: [link](https://github.com/BA5S85/health-reporter/wiki/_Deleting-clients).
