### ISSUE TITLE
Create a search functionality for clients in Clients table view

### ISSUE THREAD

**Issue by anna-bass** [health-reporter/health-reporter#29]
See the [requirement nr 4 related to clients table](https://github.com/BA5S85/health-reporter/wiki/Functional-requirements) and link to the [use case](https://github.com/BA5S85/health-reporter/wiki/_Searching-clients)

**Comment by BA5S85** [comment]
Link to the corresponding use case: [link](https://github.com/BA5S85/health-reporter/wiki/_Searching-clients).
